# Site Settings
title: mathWIKI
email: jgun0090@gmail.com
description: 수학 문제 모음집.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mathwiki.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: mathwiki
user_description: mathwiki.
disqus_username: mathwiki

# Social Media
# Remove the item if you don't need it

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
